name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  #stack:
  #  name: stack / ubuntu-latest
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      stack: ["latest"]

  #  steps:
  #  - uses: actions/checkout@v2
  #    #if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

  #  - uses: actions/setup-haskell@v1.1
  #    name: Setup Haskell Stack
  #    with:
  #      stack-version: ${{ matrix.stack }}

  #  - uses: actions/cache@v1
  #    name: Cache ~/.stack
  #    with:
  #      path: ~/.stack
  #      key: ${{ runner.os }}-${{ matrix.ghc }}-stack

  #  - name: Install Required System Packages
  #    run: sudo apt-get install gobject-introspection libgirepository1.0-dev libgtk-3-dev libvte-2.91-dev libpcre2-dev

  #  - name: Build
  #    run: |
  #      stack build --test --bench --no-run-tests --no-run-benchmarks --flag termonad:buildexamples
  #  - name: Test
  #    run: |
  #      stack test --flag termonad:buildexamples

  nix:
    name: nix / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
    - run: nix-build shell.nix
